bigbind_solv_dir: /work/users/r/d/rdey/BigBindSolvV2/BigBindSolvV2
batch_size: 100
learn_rate: 1e-4
num_epochs: 3
clip_gradients: 1
lr_scheduler: 'Exponential30' # no learning rate scheduler

logging_freq: 20

sterics_hidden_dim: 64
electrostatics_hidden_dim: 64



loss:
  force_weight: 1.0
  sterics_weight: 1.0
  electrostatics_weight: 1.0

name: MAF_MLv1
use_wandb: True
